version: '3'

services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A django_emailer worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A django_emailer beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis
